### ISSUE TITLE
'tiktok_opensdk_react_native/tiktok_opensdk_react_native-Swift.h' file not found

### ISSUE THREAD

**Issue by Splicer97** [rnheroes/tiktok-opensdk-react-native#1]

**Comment by Splicer97** [comment]
I replace it to #import ```"tiktok_opensdk_react_native-Swift.h"```

**Comment by enestatli** [comment]
@Splicer97 Did you resolve your issue? I have just sent a new release including many changes.

**Comment by NikitaKovantsovIngeneratelabs** [comment]
> @Splicer97 Did you resolve your issue? I have just sent a new release including many changes.

version 10.0.0

**Comment by Splicer97** [comment]
> @NikitaKovantsovIngeneratelabs did you run pod install?

of course

**Comment by enestatli** [comment]
@Splicer97 okay thanks, checking now

**Comment by enestatli** [comment]
@Splicer97 what's your react-native version? can you please also share your podfile.lock content (only tiktok part will be enough)

**Comment by Splicer97** [comment]
> @Splicer97 what's your react-native version? can you please also share your podfile.lock content (only tiktok part will be enough)

      "react-native": "0.73.9",
      
      podfile.lock
      ```  - tiktok-opensdk-react-native (0.10.0):
    - glog
    - RCT-Folly (= 2022.05.16.00)
    - React-Core
    - TikTokOpenSDKCore (= 2.5.0)
    - TikTokOpenShareSDK (= 2.5.0)
  - TikTokOpenSDKCore (2.5.0):
    - TikTokOpenSDKCore/Core (= 2.5.0)
  - TikTokOpenSDKCore/Core (2.5.0)
  - TikTokOpenShareSDK (2.5.0):
    - TikTokOpenSDKCore (= 2.5.0)
    - TikTokOpenShareSDK/Share (= 2.5.0)
  - TikTokOpenShareSDK/Share (2.5.0):
    - TikTokOpenSDKCore (= 2.5.0)```

**Comment by Splicer97** [comment]
> @Splicer97 thank you, I couldn't reproduce it on my side. can you verify that you import as below?
> 
> `#import <tiktok_opensdk_react_native/tiktok_opensdk_react_native-Swift.h>`

I create new repo for represent error https://github.com/Splicer97/TikTokError check plz
I use xcode 16 if its important
